version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
       - echo "Building the code..." 
  post_build:
    commands:
      - echo "Invoking Lambda function..." 
      - aws lambda invoke --function-name testing-lambda-function --region 'us-east-1' --debug
      - echo "Build completed successfully"